name: chrono_sheet
description: "A stopwatch which data is managed by Google Sheets"

publish_to: 'none'

version: 1.19.0+20

environment:
  sdk: 3.5.1
  flutter: 3.24.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 1.0.8
  firebase_core: 3.9.0
  firebase_auth: 5.3.4
  google_sign_in: 6.2.2
  googleapis: 13.2.0
  googleapis_auth: 1.6.0
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  riverpod_generator: 2.6.3
  build_runner: 2.4.13
  custom_lint: 0.7.0
  riverpod_lint: 2.6.3

flutter:
  uses-material-design: true