name: chrono_sheet
description: "A stopwatch which data is managed by Google Sheets"

publish_to: 'none'

version: 1.18.0+19

environment:
  sdk: 3.5.1
  flutter: 3.24.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 1.0.8
  firebase_core: 3.8.1
  firebase_auth: 5.3.4
  google_sign_in: 6.2.2
  googleapis: 13.2.0
  googleapis_auth: 1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:

  uses-material-design: true