name: chrono_sheet
description: "A stopwatch which data is managed by Google Sheets"

publish_to: 'none'

version: 1.103.0+104

environment:
  sdk: 3.7.0
  flutter: 3.29.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: 1.0.8
  firebase_core: 3.9.0
  firebase_auth: 5.3.4
  google_sign_in: 6.2.2
  googleapis: 13.2.0
  googleapis_auth: 1.6.0
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  go_router: 14.6.2
  logging: 1.3.0
  firebase_crashlytics: 4.2.0
  firebase_analytics: 11.3.6
  shared_preferences: 2.3.4
  uuid: 4.5.1
  http: 1.2.2
  url_launcher: 6.3.1
  connectivity_plus: 6.1.2
  path_provider: 2.1.5
  collection: 1.19.1
  file_picker: 9.0.2
  image: 4.5.2
  permission_handler: 11.4.0
  image_cropper: 9.0.0
  fpdart: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  riverpod_generator: 2.6.3
  build_runner: 2.4.13
  custom_lint: 0.7.0
  riverpod_lint: 2.6.3
  mockito: 5.4.4
