name: chrono_sheet
description: "A stopwatch which data is managed by Google Sheets"

publish_to: 'none'

version: 1.115.0+116

environment:
  sdk: 3.9.2
  flutter: 3.35.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/

flutter_native_splash:
  background_image: assets/splash/splash.png
  color: '#fff8ff'

  android_12:
    image: assets/splash/splash-square.png
    color: '#fff8ff'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: 1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.2.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  go_router: ^16.2.1
  logging: 1.3.0
  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1
  shared_preferences: ^2.5.3
  uuid: 4.5.1
  http: ^1.5.0
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0
  path_provider: 2.1.5
  collection: 1.19.1
  file_picker: ^10.3.3
  image: ^4.5.4
  permission_handler: ^12.0.1
  image_cropper: ^10.0.0+1
  fpdart: 1.1.1
  flutter_native_splash: ^2.4.6

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
  mockito: ^5.5.0
