name: prepare environment
description: common steps for setting up the environment
inputs:
  firebase-options-base64:
    description: firebase_options.dart contents encoded in base64
    required: true
  info-plist:
    description: Info.plist file, necessary for generating a splash image
    required: true
runs:
  using: "composite"
  steps:
    - name: set up flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
        cache: true

    - name: print flutter version
      shell: bash
      run: flutter --version

    - name: get dependencies
      shell: bash
      run: flutter pub get

    - name: generate l10n
      shell: bash
      run: flutter gen-l10n

    - name: prepare common sensitive data
      shell: bash
      run: |
        echo "${{ inputs.firebase-options-base64 }}" | base64 -d >> ./lib/firebase_options.dart
        
        # we need this for the icon generation
        echo "${{ inputs.info-plist }}" | base64 -d >> ./ios/Runner/Info.plist