name: build and release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: build and release
    runs-on: macos-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
